services:
  web:
    container_name: kotobamichi-web
    image: ghcr.io/infinit3hq/kotobamichi-frontend:latest
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-8080}:3000"
    restart: unless-stopped
    networks:
      - kotobamichi-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  kotobamichi-network:
    external: true
