services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:3001/v1/"
        VITE_APP_ENV: "development"
    ports:
      - "5173:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Vite env vars should be passed at build time via build.args. Runtime env can be injected via /public/env.js if needed.
