version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    # If you need to pass Vite env vars at build time, add them under build.args and use ARG in Dockerfile.
    # build:
    #   args:
    #     - VITE_API_BASE_URL=http://localhost:3000
